### ISSUE TITLE
Interpolated variable values

### ISSUE THREAD

**Issue by DaveJarvis** [michaelstepner/pandoc-mustache#5]
Given:

``` .yaml
---
a: A
b: $a$ B
c: $b$ C $b$
...
```

Produce:

``` .yaml
---
a: A
b: A B
c: A B C A B
...
```

The [algorithm](https://bitbucket.org/djarvis/yamlp/src/168add4fe1140591e059a5cb65b2bae4a6a4843a/src/main/java/com/whitemagicsoftware/yamlp/parser/YamlParser.java?at=master&fileviewer=file-view-default#YamlParser.java-242) that performs this feat is relatively trivial.

**Comment by michaelstepner** [comment]
On a quick glance at the Mustache spec, I didn't see this feature. I may have missed it though. If it's not a part of the Mustache spec, my instinct is that I wouldn't support merging a pull request that implements this. This doesn't strike me at first glance like a common use case, but I'd welcome more discussion.

I've pasted the contributing section from the README below.

> ## Contributing
>
> Project Status: Inactive
>
> This code is not being actively developed. It was created to fulfill my pandoc writing needs, and the current feature set is adequate for me.
> 
> If you have a **feature request**, it is unlikely that I will be able to implement it for you. You can create an issue to generate discussion. If you implement a feature, you can file pull request and I will review it eventually, as time permits. If you're interested in making major additions to the code, I'd be happy to welcome a new maintainer to the project.
