### ISSUE TITLE
latex expressions in variables

### ISSUE THREAD

**Issue by myutkin** [michaelstepner/pandoc-mustache#6]
Was wondering if it is possible to implement latex support in variables?

**Comment by michaelstepner** [comment]
@myutkin, it might be possible to add this feature, but I'm unlikely to implement it. I've pasted the contributing section from the README below.

> ## Contributing
>
> Project Status: Inactive
>
> This code is not being actively developed. It was created to fulfill my pandoc writing needs, and the current feature set is adequate for me.
> 
> If you have a **feature request**, it is unlikely that I will be able to implement it for you. You can create an issue to generate discussion. If you implement a feature, you can file pull request and I will review it eventually, as time permits. If you're interested in making major additions to the code, I'd be happy to welcome a new maintainer to the project.

If you'd like to spark further discussion on this feature request, you might want to describe what the current behaviour is, and what behaviour you'd like to see. A toy example would be helpful.
